"""
Flet Frontend Generator - Generates Flet-based web frontend code
"""

import os
import json
from pathlib import Path
from typing import Dict, Any
from jinja2 import Template

from core.framework import FlashFlowProject, FlashFlowIR

class FletFrontendGenerator:
    """Generates Flet-based web frontend code from FlashFlow IR"""

    def __init__(self, project: FlashFlowProject, ir: FlashFlowIR, env: str = 'development'):
        self.project = project
        self.ir = ir
        self.env = env
        self.frontend_path = project.dist_path / "frontend"

    def generate(self):
        """Generate complete frontend using Flet"""

        # Create frontend directory structure
        self._create_directory_structure()

        # Generate main app file
        self._generate_main_app()

        # Generate pages
        self._generate_pages()

        # Generate components
        self._generate_components()

        # Generate build configuration
        self._generate_build_config()

    def _create_directory_structure(self):
        """Create frontend directory structure"""

        dirs = [
            self.frontend_path,
            self.frontend_path / "src",
            self.frontend_path / "src" / "components",
            self.frontend_path / "src" / "pages",
            self.frontend_path / "src" / "utils",
            self.frontend_path / "assets"
        ]

        for dir_path in dirs:
            dir_path.mkdir(parents=True, exist_ok=True)

    def _generate_main_app(self):
        """Generate main Flet web application"""

        template = Template("""#!/usr/bin/env python3
\"\"\"
{{ project_name }} Web App
Generated by FlashFlow Flet Frontend Generator
\"\"\"

import flet as ft
import asyncio
from src.pages import *

def main(page: ft.Page):
    # Configure page
    page.title = "{{ project_name }}"
    page.theme_mode = ft.ThemeMode.LIGHT
    page.padding = 0
    page.spacing = 0
    
    # Set window properties for web
    page.window_width = 1200
    page.window_height = 800
    page.window_resizable = True
    
    # Set up navigation
    def route_change(route):
        page.views.clear()
        
        # Route to appropriate view
        if page.route == "/":
            page.views.append(home_page.build(page))
        else:
            # Default/404 view
            page.views.append(build_not_found_view(page))
        
        page.update()
    
    def view_pop(view):
        page.views.pop()
        top_view = page.views[-1]
        page.go(top_view.route)
    
    page.on_route_change = route_change
    page.on_view_pop = view_pop
    
    # Load initial view
    page.go("/")

def build_not_found_view(page: ft.Page):
    \"\"\"Build 404 not found view\"\"\"
    
    return ft.View(
        "/404",
        [
            ft.AppBar(title=ft.Text("Page Not Found"), bgcolor=ft.colors.SURFACE_VARIANT),
            ft.Container(
                content=ft.Column([
                    ft.Text("Page Not Found", size=24, weight=ft.FontWeight.BOLD),
                    ft.Text("The requested page could not be found."),
                    ft.ElevatedButton(
                        "Go Home",
                        on_click=lambda _: page.go("/")
                    )
                ], 
                alignment=ft.MainAxisAlignment.CENTER,
                horizontal_alignment=ft.CrossAxisAlignment.CENTER),
                padding=20,
                expand=True
            )
        ]
    )

if __name__ == "__main__":
    ft.app(target=main, port=8080)
""")

        main_content = template.render(
            project_name=self.project.config.name
        )

        main_file = self.frontend_path / "main.py"
        with open(main_file, 'w', encoding='utf-8') as f:
            f.write(main_content)

    def _generate_pages(self):
        """Generate pages based on IR"""
        
        pages_dir = self.frontend_path / "src" / "pages"
        pages_dir.mkdir(parents=True, exist_ok=True)
        
        # Generate home page
        home_template = Template("""import flet as ft

class HomePage:
    def build(self, page: ft.Page):
        return ft.View(
            "/",
            [
                ft.AppBar(
                    title=ft.Text("{{ project_name }}"),
                    bgcolor=ft.colors.SURFACE_VARIANT
                ),
                ft.Container(
                    content=ft.Column([
                        ft.Text("Welcome to {{ project_name }}", size=32, weight=ft.FontWeight.BOLD),
                        ft.Text("This is a Flet-based web application generated by FlashFlow", size=16),
                    ],
                    alignment=ft.MainAxisAlignment.CENTER,
                    horizontal_alignment=ft.CrossAxisAlignment.CENTER),
                    padding=20,
                    expand=True
                )
            ]
        )

home_page = HomePage()
""")
        
        home_content = home_template.render(
            project_name=self.project.config.name
        )
        
        home_file = pages_dir / "home.py"
        with open(home_file, 'w', encoding='utf-8') as f:
            f.write(home_content)
        
        # Create __init__.py for pages
        init_content = """from .home import home_page

__all__ = ["home_page"]
"""
        
        init_file = pages_dir / "__init__.py"
        with open(init_file, 'w', encoding='utf-8') as f:
            f.write(init_content)

    def _generate_components(self):
        """Generate reusable components"""
        
        components_dir = self.frontend_path / "src" / "components"
        components_dir.mkdir(parents=True, exist_ok=True)
        
        # Create __init__.py for components
        init_file = components_dir / "__init__.py"
        with open(init_file, 'w', encoding='utf-8') as f:
            f.write("# Flet components\n")

    def _generate_build_config(self):
        """Generate build configuration"""
        
        # Generate requirements.txt
        requirements_content = """flet>=0.20.0
"""
        
        requirements_file = self.frontend_path / "requirements.txt"
        with open(requirements_file, 'w', encoding='utf-8') as f:
            f.write(requirements_content)
        
        # Generate build script
        build_script = """#!/usr/bin/env python3
\"\"\"
Build script for Flet web application
\"\"\"

import subprocess
import sys

def build_web_app():
    \"\"\"Build the Flet web application\"\"\"
    try:
        # Run flet build command
        subprocess.run([sys.executable, "main.py"], check=True)
        print("✅ Web application built successfully!")
    except subprocess.CalledProcessError as e:
        print(f"❌ Build failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    build_web_app()
"""
        
        build_file = self.frontend_path / "build.py"
        with open(build_file, 'w', encoding='utf-8') as f:
            f.write(build_script)