"""
Custom Command for FlashFlow CLI
This demonstrates how to add custom commands to the FlashFlow CLI
"""

import click
import os
from pathlib import Path

@click.command()
@click.option('--name', prompt='Template name', help='Name of the custom template to create')
@click.option('--type', type=click.Choice(['component', 'page', 'layout']), 
              prompt='Template type', help='Type of template to create')
@click.option('--output', default=None, help='Output directory for the template')
def custom(name, type, output):
    """Create a custom template."""
    
    # Default output directory
    if output is None:
        output = Path.cwd() / "src" / "custom"
    
    # Create output directory if it doesn't exist
    output_path = Path(output)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Generate template based on type
    if type == 'component':
        _generate_component_template(output_path, name)
    elif type == 'page':
        _generate_page_template(output_path, name)
    elif type == 'layout':
        _generate_layout_template(output_path, name)
    
    click.echo(f"✅ Created {type} template '{name}' in {output_path}")

def _generate_component_template(output_path, name):
    """Generate a custom component template."""
    # Using triple quotes to avoid escaping issues with JSX
    template_content = '''/**
 * ''' + name + ''' Component
 * Custom component generated by FlashFlow
 */

import React from 'react';

const ''' + name + ''' = (props) => {
  const { className = '', children, ...rest } = props;
  
  return (
    <div className={`''' + name.lower() + '''-component ${className}`} {...rest}>
      <h2>''' + name + ''' Component</h2>
      <div className="component-content">
        {children}
      </div>
    </div>
  );
};

export default ''' + name + ''';
'''
    
    file_path = output_path / f"{name}.jsx"
    with open(file_path, 'w') as f:
        f.write(template_content)

def _generate_page_template(output_path, name):
    """Generate a custom page template."""
    template_content = '''/**
 * ''' + name + ''' Page
 * Custom page generated by FlashFlow
 */

import React from 'react';

const ''' + name + '''Page = () => {
  return (
    <div className="''' + name.lower() + '''-page">
      <h1>''' + name + ''' Page</h1>
      <p>This is a custom page template generated by FlashFlow.</p>
    </div>
  );
};

export default ''' + name + '''Page;
'''
    
    file_path = output_path / f"{name}Page.jsx"
    with open(file_path, 'w') as f:
        f.write(template_content)

def _generate_layout_template(output_path, name):
    """Generate a custom layout template."""
    template_content = '''/**
 * ''' + name + ''' Layout
 * Custom layout generated by FlashFlow
 */

import React from 'react';

const ''' + name + '''Layout = (props) => {
  const { children, header, footer } = props;
  
  return (
    <div className="''' + name.lower() + '''-layout">
      {header && <header className="layout-header">{header}</header>}
      <main className="layout-main">
        {children}
      </main>
      {footer && <footer className="layout-footer">{footer}</footer>}
    </div>
  );
};

export default ''' + name + '''Layout;
'''
    
    file_path = output_path / f"{name}Layout.jsx"
    with open(file_path, 'w') as f:
        f.write(template_content)