"""
Custom Generator for FlashFlow
This demonstrates how to create a custom generator with custom templates
"""

import os
import json
from pathlib import Path
from jinja2 import Template

from ..core import FlashFlowProject, FlashFlowIR

class CustomGenerator:
    """Generates custom components from FlashFlow IR"""

    def __init__(self, project: FlashFlowProject, ir: FlashFlowIR):
        self.project = project
        self.ir = ir
        self.custom_path = project.dist_path / "custom"

    def generate(self):
        """Generate custom components"""
        
        # Create custom directory structure
        self._create_directory_structure()
        
        # Generate custom components
        self._generate_custom_components()
        
        # Copy custom templates
        self._copy_custom_templates()

    def _create_directory_structure(self):
        """Create custom directory structure"""
        dirs = [
            self.custom_path,
            self.custom_path / "components",
            self.custom_path / "templates",
            self.custom_path / "utils"
        ]
        
        for dir_path in dirs:
            dir_path.mkdir(parents=True, exist_ok=True)

    def _generate_custom_components(self):
        """Generate custom components using templates"""
        
        # Example: Generate a custom dashboard component
        template_path = Path(__file__).parent.parent / "templates" / "custom_dashboard.js"
        
        # Create a simple template for demonstration
        dashboard_template = """/**
 * Custom Dashboard Component
 * Generated by FlashFlow Custom Generator
 */

class CustomDashboard {
  constructor(config) {
    this.config = config || {};
    this.title = this.config.title || 'Custom Dashboard';
    this.widgets = this.config.widgets || [];
  }

  render() {
    const widgetHtml = this.widgets.map(widget => `
      <div class="widget">
        <h3>${widget.title}</h3>
        <p>${widget.description}</p>
      </div>
    `).join('');
    
    return `
      <div class="custom-dashboard">
        <h1>${this.title}</h1>
        <div class="widgets-container">
          ${widgetHtml}
        </div>
      </div>
    `;
  }
}

export default CustomDashboard;
"""
        
        # Write the template file
        with open(template_path, 'w') as f:
            f.write(dashboard_template)
        
        # Generate the actual component file
        component_content = """/**
 * Generated Custom Dashboard
 * Based on your .flow configuration
 */

import CustomDashboard from '../templates/custom_dashboard.js';

// Dashboard configuration from .flow file
const dashboardConfig = {
  title: "{{ dashboard_title }}",
  widgets: [
    {% for widget in widgets %}
    {
      title: "{{ widget.title }}",
      description: "{{ widget.description }}"
    },
    {% endfor %}
  ]
};

const dashboard = new CustomDashboard(dashboardConfig);
document.getElementById('dashboard-container').innerHTML = dashboard.render();
"""
        
        template = Template(component_content)
        rendered_content = template.render(
            dashboard_title="My Custom Dashboard",
            widgets=[
                {"title": "Users", "description": "User management widget"},
                {"title": "Analytics", "description": "Data visualization widget"},
                {"title": "Settings", "description": "Configuration widget"}
            ]
        )
        
        component_file = self.custom_path / "components" / "CustomDashboard.js"
        with open(component_file, 'w') as f:
            f.write(rendered_content)

    def _copy_custom_templates(self):
        """Copy custom templates to the generated project"""
        import shutil
        
        # Copy all templates from the templates directory
        templates_dir = Path(__file__).parent.parent / "templates"
        target_templates_dir = self.custom_path / "templates"
        
        for template_file in templates_dir.glob("*.js"):
            target_file = target_templates_dir / template_file.name
            shutil.copy(template_file, target_file)